name: Create OCI with Terraform
on:
    workflow_dispatch:

jobs:
    OCI_IaC_Deployment:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: oracle
        
        steps:
            - name: 'Checkout'
              uses: actions/checkout@v6

            - name: 'Write Config and Key FIles'
              run: |
                mkdir ~/.oci
                echo "[DEFAULT]" >> ~/.oci/config
                echo "user=${{secrets.OCI_USER_OCID}}" >> ~/.oci/config
                echo "fingerprint=${{secrets.OCI_FINGERPRINT}}" >> ~/.oci/config
                echo "region=${{secrets.OCI_REGION}}" >> ~/.oci/config
                echo "tenancy=${{secrets.OCI_TENANCY_OCID}}" >> ~/.oci/config
                echo "key_file=~/.oci/key.pem" >> ~/.oci/config
                echo "${{secrets.OCI_KEY_FILE}}" >> ~/.oci/key.pem

           
            - name: 'Install OCI CLI'
              run: |
                curl -L -O https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
                chmod +x install.sh
                ./install.sh --accept-all-defaults
                echo "/home/runner/bin" >> $GITHUB_PATH
                exec -l $SHELL
        
            - name: 'Fix OCI Config File Permissions'
              run: |
                oci setup repair-file-permissions --file /home/runner/.oci/config
                oci setup repair-file-permissions --file /home/runner/.oci/key.pem

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Terraform Init
              id: init
              run: terraform init
                
            - name: Terraform Validate
              id: validate
              run: terraform validate
              env:
                TF_VAR_compartment_id: ${{secrets.OCI_COMPARTMENT_ID}}
        
            - name: Terraform Plan
              id: plan
              run: terraform plan
              continue-on-error: true
              env:
                TF_VAR_compartment_id: ${{secrets.OCI_COMPARTMENT_ID}}
        
            - name: Terraform Plan Status
              if: steps.plan.outcome == 'failure'
              run: exit 1

            - name: Terraform Apply
              run: terraform apply -auto-approve
              env:
                TF_VAR_compartment_id: ${{secrets.OCI_COMPARTMENT_ID}}